/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MapView: typeof import('../components/TheMap.vue')['default']
    MarkerGroup: typeof import('./../components/MarkerGroup.vue')['default']
    MarkerGroupItem: typeof import('./../components/MarkerGroupItem.vue')['default']
    MarkerItem: typeof import('./../components/MarkerItem.vue')['default']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
    TheMap: typeof import('./../components/TheMap.vue')['default']
    TheNav: typeof import('./../components/TheNav.vue')['default']
  }
}
